<?xml version="1.0"?>

<!--
Copyright 2022 Stereolabs
Copyright 2025 Husarion sp. z o.o.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->

<!-- Reference: https://github.com/stereolabs/zed-ros2-wrapper/blob/master/zed_wrapper/urdf/zed_macro.urdf.xacro -->
<robot xmlns:xacro="http://wiki.ros.org/xacro">
  <xacro:property name="M_PI" value="3.1415926535897931" />

  <xacro:macro name="zed_camera"
               params="parent_link
                       xyz:='0.0 0.0 0.0'
                       rpy:='0.0 0.0 0.0'
                       model:=zed
                       namespace:=''
                       device_namespace:=zed">

    <xacro:property name="ns" value="${namespace + '/' if namespace != '' else ''}" />

    <xacro:if value="${model == 'zed'}">
      <xacro:property name="baseline" value="0.12" />
      <xacro:property name="height" value="0.03" />
      <xacro:property name="bottom_slope" value="0.05" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="screw_offset_z" value="0.0" />
      <xacro:property name="optical_offset_x" value="-0.01" />
      <xacro:property name="mono" value="false" />
      <xacro:property name="collision">
        <origin xyz="${screw_offset_x-0.02} 0 ${screw_offset_z}" rpy="0.0 0.0 0.0" />
        <geometry>
          <box size="0.033 0.175 0.03" />
        </geometry>
      </xacro:property>
    </xacro:if>
    <xacro:if value="${model == 'zedm'}">
      <xacro:property name="baseline" value="0.063" />
      <xacro:property name="height" value="0.0265" />
      <xacro:property name="bottom_slope" value="0.0" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="screw_offset_z" value="0.0" />
      <xacro:property name="optical_offset_x" value="0.0" />
      <xacro:property name="mono" value="false" />
      <xacro:property name="collision">
        <origin xyz="${screw_offset_x+0.01} 0.008 ${screw_offset_z}" rpy="0.0 0.0 0.0" />
        <geometry>
          <box size="0.026 0.124 0.03" />
        </geometry>
      </xacro:property>
    </xacro:if>
    <xacro:if value="${model == 'zed2'}">
      <xacro:property name="baseline" value="0.12" />
      <xacro:property name="height" value="0.03" />
      <xacro:property name="bottom_slope" value="0.05" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="screw_offset_z" value="0.0" />
      <xacro:property name="optical_offset_x" value="-0.01" />
      <xacro:property name="mono" value="false" />
      <xacro:property name="collision">
        <origin xyz="${screw_offset_x} 0 ${screw_offset_z}" rpy="0.0 0.0 0.0" />
        <geometry>
          <box size="0.033 0.175 0.03" />
        </geometry>
      </xacro:property>
    </xacro:if>
    <xacro:if value="${model == 'zed2i'}">
      <xacro:property name="baseline" value="0.12" />
      <xacro:property name="height" value="0.03" />
      <xacro:property name="bottom_slope" value="0.0" />
      <xacro:property name="screw_offset_x" value="-0.01" />
      <xacro:property name="screw_offset_z" value="0.0" />
      <xacro:property name="optical_offset_x" value="-0.01" />
      <xacro:property name="mono" value="false" />
      <xacro:property name="collision">
        <origin xyz="${screw_offset_x+0.005} 0 ${screw_offset_z}" rpy="0.0 0.0 0.0" />
        <geometry>
          <box size="0.043 0.175 0.03" />
        </geometry>
      </xacro:property>
    </xacro:if>
    <xacro:if value="${model == 'zedx'}">
      <xacro:property name="baseline" value="0.12" />
      <xacro:property name="height" value="0.032" />
      <xacro:property name="bottom_slope" value="0.0" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="screw_offset_z" value="-0.016" />
      <xacro:property name="optical_offset_x" value="-0.01" />
      <xacro:property name="mono" value="false" />
      <xacro:property name="collision">
        <origin xyz="${screw_offset_x-0.005} 0 0" rpy="0.0 0.0 0.0" />
        <geometry>
          <box size="0.037 0.163 0.032" />
        </geometry>
      </xacro:property>
    </xacro:if>
    <xacro:if value="${model == 'zedxm'}">
      <xacro:property name="baseline" value="0.05" />
      <xacro:property name="height" value="0.032" />
      <xacro:property name="bottom_slope" value="0.0" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="screw_offset_z" value="-0.016" />
      <xacro:property name="optical_offset_x" value="-0.01" />
      <xacro:property name="mono" value="false" />
      <xacro:property name="collision">
        <origin xyz="${screw_offset_x-0.015} 0 0" rpy="0.0 0.0 0.0" />
        <geometry>
          <box size="0.037 0.094 0.032" />
        </geometry>
      </xacro:property>
    </xacro:if>
    <xacro:if value="${model == 'virtual'}">
      <xacro:property name="baseline" value="${custom_baseline}" />
      <xacro:property name="height" value="0.031" />
      <xacro:property name="bottom_slope" value="0.0" />
      <xacro:property name="screw_offset_x" value="0.00" />
      <xacro:property name="screw_offset_z" value="-0.0155" />
      <xacro:property name="optical_offset_x" value="0.0" />
      <xacro:property name="mono" value="false" />
      <xacro:property name="collision">
        <origin xyz="${screw_offset_x} 0 0" rpy="0.0 0.0 0.0" />
        <geometry>
          <box size="0.05 0.03 0.03" />
        </geometry>
      </xacro:property>
    </xacro:if>
    <xacro:if value="${model == 'zedxonegs'}">
      <xacro:property name="baseline" value="0.0" />
      <xacro:property name="height" value="0.031" />
      <xacro:property name="bottom_slope" value="0.0" />
      <xacro:property name="screw_offset_x" value="0.0" />
      <xacro:property name="screw_offset_z" value="-0.0155" />
      <xacro:property name="optical_offset_x" value="0.0" />
      <xacro:property name="mono" value="true" />
      <xacro:property name="collision">
        <origin xyz="${screw_offset_x} 0 0" rpy="0.0 0.0 0.0" />
        <geometry>
          <box size="0.052 0.031 0.031" />
        </geometry>
      </xacro:property>
    </xacro:if>
    <xacro:if value="${model == 'zedxone4k'}">
      <xacro:property name="baseline" value="0.0" />
      <xacro:property name="height" value="0.031" />
      <xacro:property name="bottom_slope" value="0.0" />
      <xacro:property name="screw_offset_x" value="0.00" />
      <xacro:property name="screw_offset_z" value="-0.0155" />
      <xacro:property name="optical_offset_x" value="0.0" />
      <xacro:property name="mono" value="true" />
      <xacro:property name="collision">
        <origin xyz="${screw_offset_x} 0 0" rpy="0.0 0.0 0.0" />
        <geometry>
          <box size="0.058 0.031 0.031" />
        </geometry>
      </xacro:property>
    </xacro:if>

    <!-- Camera mounting point (the threaded screw hole in the bottom) -->
    <link name="${device_namespace}_camera_link" />
    <joint name="${device_namespace}_base_joint" type="fixed">
      <parent link="${parent_link}" />
      <child link="${device_namespace}_camera_link" />
      <origin xyz="${xyz}" rpy="${rpy}" />
    </joint>

    <!-- Camera Center -->
    <link name="${device_namespace}_camera_center">
      <xacro:unless value="${model == 'virtual'}">
        <visual>
          <origin xyz="${screw_offset_x} 0 ${screw_offset_z}" rpy="0 0 0"/>
          <geometry>
          <mesh filename="package://zed_msgs/meshes/${model}.stl" />
          </geometry>
          <material name="mat">
            <color rgba="0.25 0.25 0.25 0.99" />
          </material>
        </visual>
        <collision>
          <!-- <origin xyz="${screw_offset_x} 0 ${screw_offset_z}" rpy="0 0 0"/>
          <geometry>
            <mesh filename="package://zed_msgs/meshes/${model}.stl" />
          </geometry> -->
          <!-- Use simple collision instead default stl -->
          <xacro:insert_block name="collision" />
        </collision>
      </xacro:unless>
    </link>
    <joint name="${device_namespace}_camera_center_joint" type="fixed">
      <parent link="${device_namespace}_camera_link"/>
      <child link="${device_namespace}_camera_center"/>
      <origin xyz="0 0 ${height/2}" rpy="0 ${bottom_slope} 0" />
    </joint>

    <xacro:unless value="${mono}">
      <!-- Left Camera -->
      <link name="${device_namespace}_left_camera_frame">
        <xacro:if value="${model == 'virtual'}">
          <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://zed_msgs/meshes/${model}.stl" />
            </geometry>
            <material name="mat">
              <color rgba="0.25 0.25 0.25 0.99" />
            </material>
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://zed_msgs/meshes/${model}.stl" />
            </geometry>
          </collision>
        </xacro:if>
      </link>
      <joint name="${device_namespace}_left_camera_joint" type="fixed">
        <parent link="${device_namespace}_camera_center"/>
        <child link="${device_namespace}_left_camera_frame"/>
        <origin xyz="${optical_offset_x} ${baseline/2} 0" rpy="0 0 0" />
      </joint>

      <link name="${device_namespace}_left_camera_optical_frame"/>
      <joint name="${device_namespace}_left_camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-${M_PI/2} 0.0 -${M_PI/2}"/>
        <parent link="${device_namespace}_left_camera_frame"/>
        <child link="${device_namespace}_left_camera_optical_frame"/>
      </joint>

      <!-- Right Camera -->
      <link name="${device_namespace}_right_camera_frame">
        <xacro:if value="${model == 'virtual'}">
          <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://zed_msgs/meshes/${model}.stl" />
            </geometry>
            <material name="mat">
              <color rgba="0.25 0.25 0.25 0.99" />
            </material>
          </visual>
          <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
              <mesh filename="package://zed_msgs/meshes/${model}.stl" />
            </geometry>
          </collision>
        </xacro:if>
      </link>
      <joint name="${device_namespace}_right_camera_joint" type="fixed">
        <parent link="${device_namespace}_camera_center"/>
        <child link="${device_namespace}_right_camera_frame"/>
        <origin xyz="${optical_offset_x} -${baseline/2} 0" rpy="0 0 0" />
      </joint>

      <link name="${device_namespace}_right_camera_optical_frame"/>
      <joint name="${device_namespace}_right_camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-${M_PI/2} 0.0 -${M_PI/2}"/>
        <parent link="${device_namespace}_right_camera_frame"/>
        <child link="${device_namespace}_right_camera_optical_frame"/>
      </joint>

      <!-- ZED2 Sensors -->
      <xacro:if value="${model == 'zed2'}">
        <link name="${device_namespace}_mag_link" />
        <joint name="${device_namespace}_mag_joint" type="fixed">
          <parent link="${device_namespace}_camera_center"/>
          <child link="${device_namespace}_mag_link"/>
          <origin xyz="0 0 0" rpy="0 0 0" />
        </joint>

        <link name="${device_namespace}_baro_link" />
        <joint name="${device_namespace}_baro_joint" type="fixed">
          <parent link="${device_namespace}_camera_center"/>
          <child link="${device_namespace}_baro_link"/>
          <origin xyz="0 0 0" rpy="0 0 0" />
        </joint>

        <link name="${device_namespace}_temp_left_link" />
        <joint name="${device_namespace}_temp_left_joint" type="fixed">
          <parent link="${device_namespace}_left_camera_frame"/>
          <child link="${device_namespace}_temp_left_link"/>
          <origin xyz="0 0 0" rpy="0 0 0" />
        </joint>

        <link name="${device_namespace}_temp_right_link" />
        <joint name="${device_namespace}_temp_right_joint" type="fixed">
          <parent link="${device_namespace}_right_camera_frame"/>
          <child link="${device_namespace}_temp_right_link"/>
          <origin xyz="0 0 0" rpy="0 0 0" />
        </joint>
      </xacro:if>
    </xacro:unless>

    <xacro:if value="${mono}">
      <!-- Camera -->
      <link name="${device_namespace}_camera_frame" />
      <joint name="${device_namespace}_camera_joint" type="fixed">
        <parent link="${device_namespace}_camera_center"/>
        <child link="${device_namespace}_camera_frame"/>
        <origin xyz="${optical_offset_x} 0 0" rpy="0 0 0" />
      </joint>

      <link name="${device_namespace}_camera_optical_frame"/>
      <joint name="${device_namespace}_camera_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="-${M_PI/2} 0.0 -${M_PI/2}"/>
        <parent link="${device_namespace}_camera_frame"/>
        <child link="${device_namespace}_camera_optical_frame"/>
      </joint>
    </xacro:if>

    <!-- GAZEBO -->
    <xacro:include filename="$(find husarion_components_description)/urdf/gz_sensor.urdf.xacro" ns="gz_sensor" />

    <xacro:gz_sensor.camera
      reference="${device_namespace}_camera_center"
      name="${ns}${device_namespace}_stereolabs_zed_color"
      topic="${ns}${device_namespace}/zed_node/rgb/image_rect_color"
      frame_id="${ns}${device_namespace}_camera_center"
      frequency="30"
      width="1280"
      height="720"
      fov="${110.0/180.0*pi}" />

    <xacro:gz_sensor.depth_camera
      reference="${device_namespace}_camera_center"
      name="${ns}${device_namespace}_stereolabs_zed_depth"
      topic="${ns}${device_namespace}/zed_node/depth"
      frame_id="${ns}${device_namespace}_camera_center"
      frequency="30"
      width="1280"
      height="720"
      fov="${110.0/180.0*pi}"
      min_dist="0.3"
      max_dist="20.0"
      stddev_error="0.03" />

  </xacro:macro>
</robot>
