---
# https://github.com/ros-drivers/velodyne/tree/humble-devel/velodyne_pointcloud#published-topics
  - ros_topic_name: <robot_namespace><device_namespace>/velodyne_points
    gz_topic_name: <robot_namespace><device_namespace>/velodyne_points/points
    ros_type_name: sensor_msgs/msg/PointCloud2
    gz_type_name: gz.msgs.PointCloudPacked
    lazy: true
    direction: GZ_TO_ROS
