---
/**:
  robotiq_gripper_controller:
    ros__parameters:
      default: true
      joint: robotiq_85_left_knuckle_joint
      use_effort_interface: true
      use_speed_interface: true

  robotiq_activation_controller:
    ros__parameters:
      default: true
      joint: robotiq_85_left_knuckle_joint
